### ISSUE TITLE
Consistently get "Error writing to channel" when a client try to join a session

### ISSUE THREAD

**Issue by phuongnd08** [tmate-io/tmate-ssh-server#45] opened 2018-10-22 04:33 UTC
I'm setting up my own tmate-slave (the default tmate.io seems to be overloaded)

So here what I did on my ubuntu 16.04:

```bash
apt update
apt install -y git-core build-essential pkg-config libtool libevent-dev libncurses-dev zlib1g-dev automake libssh-dev cmake ruby

# Install msgpack

curl -OL "https://github.com/msgpack/msgpack-c/releases/download/cpp-1.3.0/msgpack-1.3.0.tar.gz"
tar xzf msgpack-1.3.0.tar.gz && cd msgpack-1.3.0/
./configure --prefix=/usr && make && make install

# Install libssh

git clone https://github.com/nviennot/libssh.git
cd libssh && mkdir -p build && cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DWITH_EXAMPLES=OFF -DWITH_SFTP=OFF .. && make && make install

# Install tmate-slave

git clone https://github.com/tmate-io/tmate-slave.git && cd tmate-slave
./autogen.sh
export PKG_CONFIG_PATH=/usr/lib/pkgconfig/
./configure && make
./create_keys.sh # This will generate SSH keys, remember the keys fingerprints.
sudo ./tmate-slave

./tmate-slave -p 2222 -h [REDACTED]

```

Now Configure client `~/.tmate.conf`:

```
set -g tmate-server-host "[REDACTED]"
set -g tmate-server-port 2222
set -g tmate-server-rsa-fingerprint   "95:2b:4c:5e:90:a9:a9:79:d1:34:b9:1a:61:da:4e:31"
set -g tmate-server-ecdsa-fingerprint "09:47:d4:e4:bb:69:1a:61:17:48:b6:c5:e9:d2:2c:96"
set -g tmate-identity ""              # Can be specified to use a different SSH key.
```

After that: Start `tmate` to host a session:
```
$ tmate
[tmate] ssh session: ssh -p2222 WUFYWY8kCgSlhTrPl61EtiR30@[REDACTED]
```

But attempt to connect to such sessions yield error:
```
$ ssh -p2222 WUFYWY8kCgSlhTrPl61EtiR30@[REDACTED]
[server exited]
Connection to [REDACTED] closed by remote host.
Connection to [REDACTED] closed.

```

In tmux-slave output, here is what it printed:
```
<5> [init] (tmate) Bootstrapping ssh client ip=[REDACTED]
<5> [WUFYWY8kCgSlhTrPl61EtiR30] (tmate) Spawning slave client for [REDACTED]([REDACTED])
<5> [WUFYWY8kCgSlhTrPl61EtiR30] (tmate) Client joined (cid=0)
<4> [WUFYWY8kCgSlhTrPl61EtiR30] (tmate) Error writing to channel:
<5> [WUFYWY8kCgSlhTrPl61EtiR30] (tmate) Client left (cid=0)
```

which traced back to this:

```c
static void on_daemon_encoder_write(void *userdata, struct evbuffer *buffer)
{
        struct tmate_session *session = userdata;
        ssize_t len, written;
        unsigned char *buf;

        for(;;) {
                len = evbuffer_get_length(buffer);
                if (!len)
                        break;

                buf = evbuffer_pullup(buffer, -1);

                written = ssh_channel_write(session->ssh_client.channel, buf, len);
                if (written < 0) {
                        tmate_warn("Error writing to channel: %s",
                                    ssh_get_error(session->ssh_client.session));
                        request_server_termination();
                        break;
                }

                evbuffer_drain(buffer, written);
        }
}
```

So `ssh_channel_write` can't write and `ssh_get_error` doesn't return any clues

**Comment by amasson84** [comment] 2018-10-24 06:49
Exactly have the same problem than you with debian jessie. Using msgpack and libssh either from debian repo or from github.
I don't know how we can try to fix this ?

**Comment by phuongnd08** [comment] 2018-10-25 08:38
@amasson84 I ended up using prebuilt docker for this
https://hub.docker.com/r/sigma/tmate/
One catch is that I didn't see it print the finger print. So I had to manually enter into the container to get the fingerprint. Other than that, the docker version works like a charm.

**Comment by rrondeau** [comment] 2018-10-25 17:19
Same problem on alpine here with @sigma Dockerfile

**Comment by rrondeau** [comment] 2018-10-31 15:28
The crash is caused by this commit in libssh : https://git.libssh.org/projects/libssh.git/commit/?id=b9033ad56a498d0642f3258a54a32251278a319e
Before this commit, everything is fine

**Comment by amasson84** [comment] 2018-11-15 13:51
I found the problem (and an ok solution)
The problem comes from the keepalive ssh that apparently activates the packet filtering added in libssh to prevent some attack 
This creates an error that just crashes all the communication.
The solution I did was just to disable this keepalive and it seems to work ok
To do that 

```
in **tmate-ssh-latency.c**
//if (ssh_send_keepalive(client->session) == SSH_ERROR)
//      return;
```

I don't know if we need another way to do the keepalive because in my case I didn't loose the connection even without use. 

hope this help :)

**Comment by nviennot** [comment] 2018-11-19 02:29
Fixed in : https://github.com/tmate-io/tmate-slave/commit/8b294f32700a97ea69a6a29e2d8c38963ff3d994

Thanks @amasson84

**Comment by rrondeau** [comment] 2018-11-19 08:52
Works fine for me, Thanks

**Comment by jschaul** [comment] 2019-09-10 19:29
https://github.com/tmate-io/tmate-ssh-server/commit/8b294f32700a97ea69a6a29e2d8c38963ff3d994 does unfortunately not fix the issue also for other versions of libssh that appear problematic. For instance on ubuntu 18.04, with the following version of libssh: 

```
libssh-4/bionic-updates,bionic-security,bionic-updates,bionic-security,now 0.8.0~20170825.94fa1e38-1ubuntu0.2 amd64 [installed,automatic]
  tiny C SSH library (OpenSSL flavor)

libssh-dev/bionic-updates,bionic-security,bionic-updates,bionic-security,now 0.8.0~20170825.94fa1e38-1ubuntu0.2 amd64 [installed]
  tiny C SSH library. Development files (OpenSSL flavor)
```

the same problem can be observed. Removing the `if (ssh_version(SSH_VERSION_INT(0,8,4)))` line, i.e. returning directly after entering the `on_keepalive_timer`, fixes the problem for me. 

Could this issue be re-opened?

**Comment by antigenius0910** [comment] 2019-09-15 16:19
confirm @jschaul 's solution works on ubuntu 18.04

vim ./tmate-slave/tmate-ssh-latency.c
```
//      if (ssh_version(SSH_VERSION_INT(0,8,4)))
//              return;

//      if (ssh_send_keepalive(client->session) == SSH_ERROR)
//              return;

```

**Comment by jschaul** [comment] 2019-09-16 10:36
@antigenius0910 that's not what I meant. This is the diff that works for me: (i.e. an immediate `return;` as soon as the function is called):

```diff
--- before: /tmp/tmate-ssh-server/tmate-ssh-latency.c (content)
+++ after: /tmp/tmate-ssh-server/tmate-ssh-latency.c (content)
@@ -33,7 +33,6 @@
 	 * libssh-0.8.4 or higher have a broken keepalive implementation due
 	 * to packet filtering.
 	 */
-	if (ssh_version(SSH_VERSION_INT(0,8,4)))
 		return;
 
 	if (ssh_send_keepalive(client->session) == SSH_ERROR)
```

**Comment by nviennot** [comment] 2019-10-13 09:08
This commit: https://github.com/tmate-io/tmate-ssh-server/commit/9c3cc0e264fcd8bd72f4ce782a707794f9845c55 should fix this issue.

**Closed by nviennot** 2019-10-13 09:08 UTC
